Repository kbventures/ecommerce, pull requests merged in 2022-11, with the labels that each got.

#138 Removed Menu Underline and changed text text decoration ot non and ad…
  client/src/routes/Home/home.module.css
  client/src/routes/Menu/index.jsx
  client/src/routes/Menu/menu.module.css
Labels: enhancement

#140 Implemented CSS Design System and fixed responssive bugs
  client/src/routes/Item/Item.module.css
  client/src/routes/Item/Productinfo/Productinfo.module.css
  client/src/routes/Item/Productinfo/index.jsx
Labels: bug

#156 Removed all unecessary commentes
  client/index.js
  client/src/components/Button/button.module.css
  client/src/components/ProductsList/index.jsx
  client/src/components/Slider/index.jsx
  client/src/components/Slider/slider.module.css
  client/src/components/SliderCard/SliderCard.module.css
  client/src/contexts/BasketContext.jsx
  client/src/contexts/ItemsContext.jsx
  client/src/routes/Basket/index.jsx
  client/src/routes/Home/home.module.css
  client/src/routes/Item/Productinfo/Productinfo.module.css
  client/src/routes/Item/Productinfo/index.jsx
  client/src/routes/Menu/menu.module.css
  server/src/app.ts
  server/src/controllers/productsControllers.ts
  server/src/routes/productsRoutes.ts
Labels: documentation

#155 Updated Information In Front End Package.json file
  client/package.json
Labels: documentation

#158 Issue 149 - Fix: Added an error page
  client/public/assets/saly-17.png
  client/src/index.jsx
  client/src/routes/Item/index.jsx
  client/src/routes/NotFound/NotFound.module.css
  client/src/routes/NotFound/index.jsx
Labels: enhancement
