Repository kbventures/ecommerce, pull requests merged in 2023-02, with the labels that each got.

#169 Create vercel.json
  client/vercel.json
Labels: enhancement

#172 removed unused color variable
  client/src/index.css
Labels: good first issue

#173 README typos/links fixed, added contributor
  README.md
  client/package-lock.json
  server/package-lock.json
Labels: documentation
